# Generated by Django 3.0.8 on 2020-07-31 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('coupon_number', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=45)),
                ('pateint_ph', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='enter 10 digit phone number', regex='^\\w{10}$')])),
                ('pro_code', models.CharField(max_length=5)),
                ('coupon_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
