# Generated by Django 3.0.8 on 2020-07-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='coupon_status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
