# Generated by Django 3.0.8 on 2020-07-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient_coupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='coupon_status',
            field=models.BooleanField(default=None),
        ),
    ]
