# Generated by Django 3.0.8 on 2020-07-31 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200731_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='coupon_status',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='enter 1 or 0', regex='^\\w{1}$')]),
        ),
    ]
