# Generated by Django 3.0.8 on 2020-07-31 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200801_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='coupon_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pateint_ph',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='enter 10 digit phone number', regex='^\\w{10}$')]),
        ),
    ]
