# Generated by Django 3.0.8 on 2020-08-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200801_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='coupon_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pateint_ph',
            field=models.IntegerField(),
        ),
    ]
