# Generated by Django 3.0.8 on 2020-08-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200801_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='coupon_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pateint_ph',
            field=models.CharField(max_length=15),
        ),
    ]
