# Generated by Django 3.0.8 on 2020-08-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200801_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pateint_ph',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_ph',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
